// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc9Kg_xhyCi-QLjQoT5SeKg3KI7iSwj_A',
    appId: '1:394595543287:web:7bedbba6a98ebc6a42cbf2',
    messagingSenderId: '394595543287',
    projectId: 'percasitasikmalaya',
    authDomain: 'percasitasikmalaya.firebaseapp.com',
    storageBucket: 'percasitasikmalaya.appspot.com',
    measurementId: 'G-PXNRS7GXQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCzgDL48PJdw9F_0joWIT031mI9wyVPrY',
    appId: '1:394595543287:android:1ecac71b6277cbcd42cbf2',
    messagingSenderId: '394595543287',
    projectId: 'percasitasikmalaya',
    storageBucket: 'percasitasikmalaya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJD1iU5LOVc_6svMuRBdQWNXHj9MmnoGA',
    appId: '1:394595543287:ios:d09023e268bf387042cbf2',
    messagingSenderId: '394595543287',
    projectId: 'percasitasikmalaya',
    storageBucket: 'percasitasikmalaya.appspot.com',
    iosBundleId: 'com.example.percasiTasikmalaya',
  );
}
